global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    static_configs:
      - targets: ['host.docker.internal:9095']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
