// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PickPoints_Read_FullMethodName   = "/pickpoints.PickPoints/Read"
	PickPoints_Create_FullMethodName = "/pickpoints.PickPoints/Create"
	PickPoints_Update_FullMethodName = "/pickpoints.PickPoints/Update"
	PickPoints_Delete_FullMethodName = "/pickpoints.PickPoints/Delete"
)

// PickPointsClient is the client API for PickPoints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PickPointsClient interface {
	Read(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*PickPointResponse, error)
	Create(ctx context.Context, in *PickPointRequest, opts ...grpc.CallOption) (*PickPointResponse, error)
	Update(ctx context.Context, in *PickPointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pickPointsClient struct {
	cc grpc.ClientConnInterface
}

func NewPickPointsClient(cc grpc.ClientConnInterface) PickPointsClient {
	return &pickPointsClient{cc}
}

func (c *pickPointsClient) Read(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*PickPointResponse, error) {
	out := new(PickPointResponse)
	err := c.cc.Invoke(ctx, PickPoints_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pickPointsClient) Create(ctx context.Context, in *PickPointRequest, opts ...grpc.CallOption) (*PickPointResponse, error) {
	out := new(PickPointResponse)
	err := c.cc.Invoke(ctx, PickPoints_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pickPointsClient) Update(ctx context.Context, in *PickPointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PickPoints_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pickPointsClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PickPoints_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PickPointsServer is the server API for PickPoints service.
// All implementations must embed UnimplementedPickPointsServer
// for forward compatibility
type PickPointsServer interface {
	Read(context.Context, *IdRequest) (*PickPointResponse, error)
	Create(context.Context, *PickPointRequest) (*PickPointResponse, error)
	Update(context.Context, *PickPointRequest) (*emptypb.Empty, error)
	Delete(context.Context, *IdRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPickPointsServer()
}

// UnimplementedPickPointsServer must be embedded to have forward compatible implementations.
type UnimplementedPickPointsServer struct {
}

func (UnimplementedPickPointsServer) Read(context.Context, *IdRequest) (*PickPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedPickPointsServer) Create(context.Context, *PickPointRequest) (*PickPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPickPointsServer) Update(context.Context, *PickPointRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPickPointsServer) Delete(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPickPointsServer) mustEmbedUnimplementedPickPointsServer() {}

// UnsafePickPointsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PickPointsServer will
// result in compilation errors.
type UnsafePickPointsServer interface {
	mustEmbedUnimplementedPickPointsServer()
}

func RegisterPickPointsServer(s grpc.ServiceRegistrar, srv PickPointsServer) {
	s.RegisterService(&PickPoints_ServiceDesc, srv)
}

func _PickPoints_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickPointsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PickPoints_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickPointsServer).Read(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PickPoints_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickPointsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PickPoints_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickPointsServer).Create(ctx, req.(*PickPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PickPoints_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickPointsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PickPoints_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickPointsServer).Update(ctx, req.(*PickPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PickPoints_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickPointsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PickPoints_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickPointsServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PickPoints_ServiceDesc is the grpc.ServiceDesc for PickPoints service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PickPoints_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pickpoints.PickPoints",
	HandlerType: (*PickPointsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _PickPoints_Read_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PickPoints_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PickPoints_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PickPoints_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
