# Server configuration
server:
  port: ":9000"
  secure_port: ":9001"

# Database credentials
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  dbname: "postgres"

# Users data
users:
  - login: "admin"
    password: "password"
