version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  postgres_test:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
